---
title: ERD
config:
 theme: default
 layout: elk
---
erDiagram
    roles ||--o{ users : "has"
    items ||--o{ stocks : "has"
    items ||--o{ transaction_details : "has"
    measurement_units ||--o{ stocks : "uses"
    measurement_units ||--o{ transaction_details : "uses"
    recipients ||--o{ transactions : "receives"
    transactions ||--o{ transaction_details : "contains"

    roles {
        string id PK
        string name UK
    }

    users {
        string id PK
        string name
        string username UK
        string password
        string role_id FK
        string profile_photo_path
        string remember_token
        timestamp created_at
        timestamp updated_at
        timestamp deleted_at
    }

    settings {
        string id PK
        string key
        string value
    }

    measurement_units {
        string id PK
        string name UK
        timestamp created_at
        timestamp updated_at
        timestamp deleted_at
    }

    items {
        string id PK
        string name
        timestamp created_at
        timestamp updated_at
        timestamp deleted_at
    }

    stocks {
        string id PK
        string item_id FK
        string unit_id FK
        integer quantity
        timestamp created_at
        timestamp updated_at
        timestamp deleted_at
    }

    recipients {
        string id PK
        string name
        string nickname
        string division
        timestamp created_at
        timestamp updated_at
        timestamp deleted_at
    }

    transactions {
        string id PK
        enum type "in/out"
        string recipient_id FK
        string supplier
        string division
        text notes
        date transaction_date
        timestamp created_at
        timestamp updated_at
        timestamp deleted_at
    }

    transaction_details {
        string id PK
        string transaction_id FK
        string item_id FK
        string unit_id FK
        integer quantity
        timestamp created_at
        timestamp updated_at
        timestamp deleted_at
    }