---
# title: "Flowchart Proses Manajemen Stok Gudang"
config:
    theme: neutral
---
flowchart TD
    START((Mulai))
    START --> STEP1[Barang masuk atau keluar dari gudang]
    STEP1 --> STEP2[/Pegawai mencatat  transaksi dan stok barang/]
    STEP2 --> STEP3[Pegawai mencatat dan menghitung stok setelah transaksi]
    STEP3 --> STEP4[Pegawai memeriksa catatan dan stok barang]
    STEP4 --> END((Akhir))